enum WidgetDirections { horizontal, vertical }
enum ChildrenOrientation { Row, Column }
enum ButtonDialog { OK, CHANGE, CANCEL, CHANGEANDCANCEL, ACTIONS, NULL }
enum ButtonType { Text, IconText }
enum AnimationDo {
  FadeIn,
  FadeInDown,
  FadeInDownBig,
  FadeInUp,
  FadeInUpBig,
  FadeInLeft,
  FadeInLeftBig,
  FadeInRight,
  FadeInRightBig,
  FadeOut,
  FadeOutDown,
  FadeOutDownBig,
  FadeOutUp,
  FadeOutUpBig,
  FadeOutLeft,
  FadeOutLeftBig,
  FadeOutRight,
  FadeOutRightBig,
  BounceInDown,
  BounceInUp,
  BounceInLeft,
  BounceInRight,
  ElasticIn,
  ElasticInDown,
  ElasticInUp,
  ElasticInLeft,
  ElasticInRight,
  SlideInDown,
  SlideInUp,
  SlideInLeft,
  SlideInRight,
  FlipInX,
  FlipInY,
  ZoomIn,
  ZoomOut,
  JelloIn,
  Bounce,
  Flash,
  Pulse,
  Swing,
  Spin,
  SpinPerfect,
  Dance,
  Roulette
}
